export const WORKFLOW_START_MESSAGES = {
  PAGE_TITLE: 'สร้าง Workflow',
  STEP1_LABEL: 'ตรวจสอบ Document',
  STEP2_LABEL: 'เลือก Template',
  STEP3_LABEL: 'ยืนยัน',
  STEP1_CARD_TITLE: 'ตรวจสอบเอกสาร',
  STEP1_INPUT_LABEL: 'รหัสเอกสาร',
  STEP1_INPUT_PLACEHOLDER: 'กรอกรหัสเอกสาร',
  STEP1_BUTTON_CHECK: 'ถัดไป →',
  STEP1_BUTTON_CHECKING: 'กำลังตรวจสอบ...',
  STEP1_WARNING: 'เอกสารนี้มี Workflow อยู่แล้ว',
  STEP1_LINK_VIEW: 'ดู Workflow →',
  STEP2_CARD_TITLE: 'เลือก Template',
  STEP2_SELECT_LABEL: 'Workflow Template',
  STEP2_SELECT_PLACEHOLDER: '-- เลือก Template --',
  STEP2_LOADING: 'กำลังโหลด template...',
  STEP2_STEPS_TITLE: 'ขั้นตอนใน Template',
  STEP2_USER_ID_LABEL: 'User ID',
  STEP2_USER_ID_INVALID: 'User ID ต้องมี @',
  STEP2_ROLE_LABEL: 'Role',
  STEP2_ROLE_PLACEHOLDER: '-- เลือก Role --',
  STEP2_REMOVE_ASSIGNEE_TITLE: 'ลบ assignee',
  STEP2_ADD_ASSIGNEE_PREFIX: '+ เพิ่ม Assignee ใน Step',
  STEP3_CARD_TITLE: 'ยืนยันข้อมูล',
  STEP3_DOC_ID_LABEL: 'รหัสเอกสาร:',
  STEP3_BUSINESS_TYPE_LABEL: 'Business Type:',
  STEP3_TEMPLATE_LABEL: 'Template:',
  STEP3_STEPS_TITLE: 'ขั้นตอน:',
  STEP3_USER_ID_PREFIX: 'User ID:',
  STEP3_ROLE_PREFIX: 'Role:',
  BUTTON_BACK: '← ย้อนกลับ',
  BUTTON_NEXT: 'ถัดไป →',
  BUTTON_SUBMIT: 'ยืนยัน',
  BUTTON_SUBMITTING: 'กำลังสร้าง...',
  TOAST_SUCCESS: 'สร้าง Workflow สำเร็จ',
};
