export const WORKFLOW_START_SELECTORS = {
  CONTAINER: 'workflow-start-container',
  TITLE: 'workflow-start-title',
  WIZARD_STEPS: 'workflow-start-wizard-steps',
  WIZARD_STEP_1: 'workflow-start-wizard-step-1',
  WIZARD_STEP_2: 'workflow-start-wizard-step-2',
  WIZARD_STEP_3: 'workflow-start-wizard-step-3',
  STEP1_CARD: 'workflow-start-step1-card',
  STEP1_INPUT: 'workflow-start-step1-input',
  STEP1_BUTTON_CHECK: 'workflow-start-step1-button-check',
  STEP1_WARNING: 'workflow-start-step1-warning',
  STEP1_LINK_VIEW: 'workflow-start-step1-link-view',
  STEP1_ERROR: 'workflow-start-step1-error',
  STEP2_CARD: 'workflow-start-step2-card',
  STEP2_SELECT: 'workflow-start-step2-select',
  STEP2_LOADING: 'workflow-start-step2-loading',
  STEP2_TEMPLATE_PREVIEW: 'workflow-start-step2-template-preview',
  STEP2_BUTTON_BACK: 'workflow-start-step2-button-back',
  STEP2_BUTTON_NEXT: 'workflow-start-step2-button-next',
  STEP3_CARD: 'workflow-start-step3-card',
  STEP3_SUMMARY: 'workflow-start-step3-summary',
  STEP3_ERROR: 'workflow-start-step3-error',
  STEP3_BUTTON_BACK: 'workflow-start-step3-button-back',
  STEP3_BUTTON_SUBMIT: 'workflow-start-step3-button-submit',
  TOAST_SUCCESS: 'workflow-start-toast-success',
};
