export const DOCUMENT_NUMBER_LIST_MESSAGES = {
  PAGE_TITLE: 'จัดการเลขเอกสาร',
  PAGE_SUBTITLE: 'จัดการรูปแบบเลขเอกสารและติดตาม running number ของแต่ละรหัส',
  CONFIG_CODE_LABEL: 'รหัสนโยบาย',
  CONFIG_CODE_PLACEHOLDER: 'ค้นหา Policy Code หรือคำอธิบาย เช่น FX_ENROLLMENT',
  ADD_BUTTON: 'เพิ่มข้อมูล',
  API_DEMO_BUTTON: 'ตัวอย่างการใช้งาน API',
  REFRESH_BUTTON: 'รีเฟรช',
  FILTER_BUTTON: 'กรองข้อมูล',
  FILTER_PANEL_TITLE: 'กรองข้อมูล',
  FILTER_POLICY_LABEL: 'รหัสนโยบาย',
  FILTER_CLEAR: 'ล้างค่า',
  FILTER_CANCEL: 'ยกเลิก',
  FILTER_APPLY: 'นำไปใช้',
  POLICY_NOT_FOUND_ERROR: 'ไม่พบรหัสนโยบายที่ระบุ',
  POLICY_LOAD_ERROR: 'ไม่สามารถโหลดรายการนโยบายได้',
  TRACKED_CODES_LABEL: 'กรองตาม :',
  TOTAL_LABEL: 'แสดงผลลัพธ์',
  TOTAL_UNIT: 'ชุด',
  LOAD_PARTIAL_WARNING: 'ไม่สามารถโหลดข้อมูลบางรายการได้',
  TABLE_COL_NO: 'ลำดับ',
  TABLE_COL_CONFIG_CODE: 'รหัส',
  TABLE_COL_POLICY_DESCRIPTION: 'คำอธิบาย',
  TABLE_COL_POLICY_STATUS: 'สถานะนโยบาย',
  TABLE_COL_FORMAT_PATTERN: 'รูปแบบเอกสาร',
  TABLE_COL_RESET_CYCLE: 'รอบรีเซ็ต',
  TABLE_COL_CURRENT_NUMBER: 'เลขล่าสุด',
  TABLE_COL_NEXT_DOCUMENT_NUMBER: 'เลขถัดไป',
  TABLE_COL_LAST_RESET_AT: 'รีเซ็ตล่าสุด',
  TABLE_COL_ACTIONS: 'การจัดการ',
  VIEW_BUTTON: 'แก้ไข/ดูรายละเอียด',
  RESET_BUTTON: 'รีเซ็ต',
  LOADING: 'กำลังโหลดข้อมูล...',
  NO_DATA: 'ไม่พบข้อมูล',
  EMPTY_CONFIG_HINT: 'กรุณาเพิ่มรหัสอย่างน้อย 1 รายการ',
  RESET_MODAL_TITLE: 'ยืนยันการรีเซ็ตเลขเอกสาร',
  RESET_MODAL_DESC: 'เมื่อรีเซ็ตแล้ว เลขปัจจุบันจะกลับไปเริ่มต้นตามค่าที่ระบบกำหนด',
  RESET_MODAL_CONFIRM: 'ยืนยันรีเซ็ต',
  RESET_MODAL_CANCEL: 'ยกเลิก',
  RESET_SUCCESS: 'รีเซ็ตเลขเอกสารสำเร็จ',
  LOAD_ERROR: 'ไม่สามารถโหลดข้อมูลได้',
  RESET_ERROR: 'ไม่สามารถรีเซ็ตเลขเอกสารได้',
} as const;
