export const TERM_CREATE_MESSAGES = {
  BREADCRUMB_HOME: 'ข้อกำหนดและเงื่อนไข',
  BREADCRUMB_DETAIL: 'รายละเอียด',
  BREADCRUMB_CREATE: 'สร้างข้อกำหนดและเงื่อนไขใหม่',
  BREADCRUMB_CREATE_VERSION: 'สร้างเวอร์ชันใหม่',
  PAGE_TITLE: 'สร้างข้อกำหนดและเงื่อนไขใหม่',
  DEFAULT_TITLE_LABEL: 'ข้อกำหนดและเงื่อนไข',
  TITLE_EDIT_BTN: 'เปลี่ยนชื่อข้อกำหนดและเงื่อนไข',
  TITLE_MODAL_TITLE: 'เปลี่ยนชื่อข้อกำหนดและเงื่อนไข',
  TITLE_MODAL_BTN_CANCEL: 'ยกเลิก',
  TITLE_MODAL_BTN_SAVE: 'บันทึก',
  VERSION_BADGE: 'Ver. ใหม่',
  LABEL_CODE: 'รหัส',
  COPY_FROM_PREFIX: 'เนื้อหาด้านล่างถูกคัดลอกมาจาก',
  BTN_START_BLANK: 'เริ่มจากหน้าว่าง',
  FIELD_TITLE: 'ชื่อข้อกำหนดและเงื่อนไข',
  FIELD_TITLE_PLACEHOLDER: 'กรอกชื่อข้อกำหนดและเงื่อนไข',
  FIELD_CUSTOMER_TYPE: 'ระดับผู้ดำเนินการ',
  CUSTOMER_TYPE_PLACEHOLDER: 'เลือกระดับผู้ดำเนินการ',
  CUSTOMER_TYPE_INDIVIDUAL: 'ผู้ใช้งาน',
  CUSTOMER_TYPE_CORPORATE: 'นิติบุคคล',
  FIELD_SERVICE: 'บริการ',
  SERVICE_PLACEHOLDER: 'กรุณาเลือกบริการ',
  FIELD_SERVICE_REQUIRED: 'กรุณาเลือกบริการ',
  FIELD_CONDITION_TYPE: 'ประเภทข้อกำหนด',
  CONDITION_TYPE_PLACEHOLDER: 'เลือกประเภทข้อกำหนด',
  FIELD_CONDITION_TYPE_REQUIRED: 'กรุณาเลือกประเภทข้อกำหนด',
  CONDITION_TYPE_MANDATORY: 'บังคับ',
  CONDITION_TYPE_OPTIONAL: 'ไม่บังคับ',
  FIELD_TYPE: 'ประเภทข้อกำหนด',
  TYPE_MANDATORY: 'บังคับ',
  TYPE_OPTIONAL: 'ไม่บังคับ',
  FIELD_CONDITION_TITLE: 'คำอธิบายวัตถุประสงค์เพื่อประกอบข้อกำหนดและเงื่อนไข',
  FIELD_CONDITION_TITLE_PLACEHOLDER:
    'เช่น ข้าพเจ้าได้อ่าน ทำความเข้าใจ และยอมรับข้อกำหนดและเงื่อนไขการใช้งานของธนาคารแล้ว',
  FIELD_CONDITION_TITLE_REQUIRED:
    'กรุณากรอกคำอธิบายวัตถุประสงค์เพื่อประกอบข้อกำหนดและเงื่อนไข',
  CHANGE_TYPE_LABEL: 'ประเภทการเปลี่ยนเวอร์ชัน',
  CHANGE_TYPE_MAJOR: 'Major — เปลี่ยนเวอร์ชันหลัก (ผู้ใช้ต้องยอมรับใหม่)',
  CHANGE_TYPE_MINOR: 'Minor — เปลี่ยนเวอร์ชันย่อย (ไม่ต้องยอมรับใหม่)',
  FIELD_CONTENT: 'รายละเอียดของข้อกำหนดและเงื่อนไข',
  FIELD_CONTENT_PLACEHOLDER: 'กรุณากรอกคำอธิบาย...',
  FIELD_CONTENT_REQUIRED: 'กรุณากรอกรายละเอียดของข้อกำหนดและเงื่อนไข',
  FIELD_CUSTOMER_TYPE_REQUIRED: 'กรุณาเลือกระดับผู้ดำเนินการ',
  REQUIRED_TEXT: 'จำเป็นต้องกรอก',
  BTN_PREVIEW: 'ดูตัวอย่าง',
  PREVIEW_MODAL_TITLE: 'ดูตัวอย่างข้อกำหนดและเงื่อนไข',
  PREVIEW_MODAL_EMPTY: 'ยังไม่มีเนื้อหาสำหรับแสดงตัวอย่าง',
  PREVIEW_MODAL_NO_CONDITION_TITLE: 'ยังไม่ได้ระบุคำอธิบายวัตถุประสงค์',
  PREVIEW_MODAL_CLOSE: 'ปิดหน้าต่างดูตัวอย่าง',
  FOOTER_NOTE: `การบันทึกจะสร้างรายการในสถานะ Inactive หากต้องการเผยแพร่ กรุณาปรับสถานะผ่านเมนู "ข้อกำหนดและเงื่อนไข"`,
  BTN_SAVE: 'บันทึก',
  VALIDATION_REQUIRED: 'กรุณากรอกข้อมูลให้ครบทุกช่อง',
  MODAL_TITLE: 'ต้องการเริ่มดำเนินการจากหน้าว่างหรือไม่?',
  MODAL_BODY: 'การเปลี่ยนแปลงใดๆที่คุณดำเนินการจะไม่ถูกบันทึก',
  MODAL_BTN_CANCEL: 'ยกเลิก',
  MODAL_BTN_CONFIRM_CLEAR: 'เริ่มจากหน้าว่าง',
  TOAST_SAVE_SUCCESS: 'บันทึกสำเร็จ',
  TOAST_SAVE_ERROR: 'เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง',
} as const;
