export const DATA_MANAGEMENT_TABLE_MESSAGES = {
  SEARCH_PLACEHOLDER: 'ค้นหารหัส หรือชื่อ',
  FILTER_BUTTON: 'กรองข้อมูล',
  FILTER_PANEL_TITLE: 'กรองข้อมูล',
  FILTER_CLEAR: 'ล้างค่า',
  FILTER_STATUS_LABEL: 'สถานะ',
  FILTER_CANCEL: 'ยกเลิก',
  FILTER_APPLY: 'นำไปใช้',
  FILTER_BY_LABEL: 'กรองตาม :',
  DOWNLOAD_BUTTON: 'ดาวน์โหลด',
  DOWNLOAD_TEMPLATE: 'ดาวน์โหลดเทมเพลต',
  DOWNLOAD_DATA: 'ดาวน์โหลดชุดข้อมูล',
  IMPORT_BUTTON: 'นำเข้าชุดข้อมูล',
  ADD_BUTTON: 'เพิ่มข้อมูล',
  TOTAL_LABEL: 'แสดงผลลัพธ์',
  TOTAL_UNIT: 'ชุด',
  COL_NO: 'ลำดับที่',
  COL_CODE: 'รหัส',
  COL_NAME: 'ชื่อ (TH)',
  COL_NAME_EN: 'ชื่อ (EN)',
  COL_STATUS: 'สถานะ',
  STATUS_ACTIVE: 'Active',
  STATUS_INACTIVE: 'Inactive',
  EDIT_TOOLTIP: 'แก้ไข',
  DELETE_TOOLTIP: 'ลบ',
  SELECTION_LABEL: 'ชุดข้อมูลที่เลือกอยู่',
  BULK_DELETE_BUTTON: 'ลบข้อมูล',
  DELETE_CONFIRM_TITLE: 'คุณต้องการลบข้อมูลหรือไม่?',
  DELETE_CONFIRM_DESC: 'หากลบแล้ว จะไม่สามารถเรียกข้อมูลที่ลบแล้วกลับมาได้',
  DELETE_CONFIRM_CANCEL: 'ยกเลิกลบข้อมูล',
  DELETE_CONFIRM_OK: 'ยืนยันลบข้อมูล',
  DELETE_SUCCESS: 'ลบข้อมูลสำเร็จ',
  DELETE_ERROR: 'เกิดข้อผิดพลาด ไม่สามารถลบข้อมูลได้ กรุณาลองใหม่อีกครั้ง',
  IMPORT_MODAL_TITLE: 'นำเข้าชุดข้อมูล',
  IMPORT_DRAG_TITLE: 'ลากและวางไฟล์ได้ที่นี่',
  IMPORT_FORMAT_HINT: 'รูปแบบไฟล์ที่รองรับ: csv, xlsx',
  IMPORT_SIZE_HINT: 'ขนาดไฟล์สูงสุด: 300 MB',
  IMPORT_OR: 'หรือ',
  IMPORT_SELECT_FILE: 'เลือกไฟล์',
  IMPORT_SUBMIT: 'นำเข้าข้อมูล',
  IMPORT_SUCCESS_TOAST: 'นำเข้าข้อมูลสำเร็จ',
  IMPORT_FAULT_HEADING: 'ตารางไม่ตรงกับ master',
  IMPORT_FAULT_DESC:
    'คอลัมน์ของไฟล์ไม่ตรงกับต้นแบบที่กำหนด กรุณาดาวน์โหลด template และกรอกข้อมูลใหม่อีกครั้ง',
  IMPORT_MOCK_FAULT: 'จำลอง: ตารางไม่ตรงกับ master',
  IMPORT_PROCESSING_BANNER: 'กำลังประมวลผลข้อมูล กรุณารอสักครู่',
  IMPORT_FILE_CHANGE: 'แก้ไข',
  IMPORT_NETWORK_ERROR: 'อัปโหลดผิดพลาด กรุณาลองใหม่อีกครั้ง',
  IMPORT_FORMAT_ERROR:
    'ไม่รองรับนามสกุลไฟล์นี้ กรุณาอัปโหลดไฟล์นามสกุล .csv, .xlsx',
  IMPORT_SIZE_ERROR: 'ขนาดไฟล์เกิน 300 MB กรุณาอับโหลดไฟล์ที่มีขนาดไฟล์เล็กลง',
  IMPORT_COLUMNS_ERROR: 'คอลัมน์ของข้อมูลไม่ครบด้วย: {columns}',
  IMPORT_MOCK_COLUMNS: 'จำลอง: คอลัมน์ไม่ครบ',
};
