export const APPLICATION_TERM_DETAIL_MESSAGES = {
  BREADCRUMB_HOME: 'ข้อกำหนดและเงื่อนไข',
  BTN_CREATE_VERSION: '+ สร้าง Version ใหม่',
  INFO_CODE: 'รหัส',
  INFO_TYPE: 'ประเภท',
  INFO_VERSION_COUNT: 'จำนวน Version (Ver. ล่าสุด)',
  INFO_LAST_UPDATED: 'อัปเดตล่าสุด',
  INFO_CREATED_BY: 'สร้างโดย',
  COL_VERSION: 'Version',
  COL_ADDED_AT: 'เพิ่มเมื่อ',
  COL_ADDED_BY: 'เพิ่มโดย',
  COL_STATUS: 'สถานะ',
  BTN_DETAIL: 'รายละเอียด',
  BTN_OPERATORS: 'ผู้ดำเนินการ',
  TYPE_MANDATORY: 'บังคับ',
  STATUS_PUBLISHED: 'Published',
  STATUS_INACTIVE: 'Inactive',
  EMPTY: 'ไม่มีข้อมูล',
  NOT_FOUND: 'ไม่พบข้อมูล',
  MODAL_EDIT_TITLE: 'แก้ไขสถานะ',
  MODAL_STATUS_PUBLISHED: 'Published',
  MODAL_STATUS_PUBLISHED_DESC: 'ผู้ใช้งานสามารถใช้งานได้ตามปกติ',
  MODAL_STATUS_INACTIVE: 'Inactive',
  MODAL_STATUS_INACTIVE_DESC: 'ผู้ใช้งานจะไม่เห็นแอปพลิเคชันย่อยนี้',
  MODAL_CHANGE_TYPE_LABEL: 'ประเภทการเปลี่ยนแปลงเวอร์ชัน',
  MODAL_CHANGE_TYPE_MAJOR: 'Major — เปลี่ยนเวอร์ชันหลัก',
  MODAL_CHANGE_TYPE_MAJOR_DESC:
    'เช่น v1.0 → v2.0 ผู้ใช้งานต้องยอมรับเงื่อนไขใหม่อีกครั้ง',
  MODAL_CHANGE_TYPE_MINOR: 'Minor — เปลี่ยนเวอร์ชันย่อย',
  MODAL_CHANGE_TYPE_MINOR_DESC:
    'เช่น v1.0 → v1.1 ไม่ต้องให้ผู้ใช้งานยอมรับเงื่อนไขใหม่',
  MODAL_BTN_CANCEL: 'ยกเลิก',
  MODAL_BTN_SAVE: 'บันทึกค่า',
} as const;
