export const APPLICATION_TERM_HOME_MESSAGES = {
  PAGE_TITLE: 'ข้อกำหนดและเงื่อนไข',
  PAGE_SUBTITLE: 'จัดการ สร้าง และตรวจสอบ Version ของข้อกำหนดและเงื่อนไข',
  BTN_CREATE: 'สร้างข้อกำหนดและเงื่อนไขใหม่',
  TAB_USER: 'ผู้ใช้งาน',
  TAB_CORPORATE: 'นิติบุคคล',
  SEARCH_PLACEHOLDER: 'ค้นหาจากรหัส ข้อตกลง หรือบริการ',
  BTN_FILTER: 'กรองข้อมูล',
  FILTER_BY: 'กรองตาม:',
  RESULT_COUNT: (count: number) => `แสดงผลลัพธ์: ${count.toLocaleString()} ชุด`,
  COL_CODE: 'รหัส',
  COL_TERM: 'ข้อตกลง',
  COL_SERVICE: 'บริการ',
  COL_LATEST_VERSION: 'Ver. ล่าสุด',
  COL_LAST_UPDATED: 'อัปเดตล่าสุด',
  COL_TYPE: 'ประเภท',
  COL_STATUS: 'สถานะ',
  TYPE_MANDATORY: 'บังคับ',
  TYPE_NON_MANDATORY: 'ไม่บังคับ',
  STATUS_PUBLISHED: 'Published',
  STATUS_INACTIVE: 'Inactive',
  EMPTY: 'ไม่มีข้อมูล',
  // Filter panel
  FILTER_PANEL_TITLE: 'กรองข้อมูล',
  FILTER_CLEAR: 'ล้างค่า',
  FILTER_SECTION_TYPE: 'ประเภท',
  FILTER_TYPE_MANDATORY: 'บังคับ',
  FILTER_TYPE_NON_MANDATORY: 'ไม่บังคับ',
  FILTER_SECTION_STATUS: 'สถานะ',
  FILTER_STATUS_ACCEPTED: 'Published',
  FILTER_STATUS_NOT_ACCEPTED: 'Inactive',
  FILTER_BTN_CANCEL: 'ยกเลิก',
  FILTER_BTN_APPLY: 'นำไปใช้',
} as const;
