export const DOCUMENT_NUMBER_DETAIL_MESSAGES = {
  BACK_BUTTON: 'กลับไปหน้ารายการ',
  PAGE_TITLE_PREFIX: 'รายละเอียดเลขเอกสาร',
  GENERATE_BUTTON: 'ทดสอบ Generate',
  RESET_BUTTON: 'รีเซ็ตเลข',
  REFRESH_BUTTON: 'รีเฟรช',
  CARD_TITLE: 'สถานะเลขเอกสารปัจจุบัน',
  FIELD_CONFIG_CODE: 'รหัสการตั้งค่า',
  FIELD_FORMAT_PATTERN: 'รูปแบบเลขเอกสาร',
  FIELD_RESET_CYCLE: 'รอบรีเซ็ต',
  FIELD_CURRENT_NUMBER: 'เลขปัจจุบัน',
  FIELD_NEXT_DOCUMENT_NUMBER: 'เลขถัดไป',
  FIELD_LAST_RESET_AT: 'รีเซ็ตล่าสุด',
  GENERATED_SUCCESS_PREFIX: 'สร้างเลขเอกสารสำเร็จ:',
  RESET_SUCCESS_PREFIX: 'รีเซ็ตสำเร็จ:',
  RESET_MODAL_TITLE: 'ยืนยันการรีเซ็ตเลขเอกสาร',
  RESET_MODAL_DESC: 'การดำเนินการนี้จะรีเซ็ต running number ของรหัสนี้ทันที',
  RESET_MODAL_CONFIRM: 'ยืนยันรีเซ็ต',
  RESET_MODAL_CANCEL: 'ยกเลิก',
  LOADING: 'กำลังโหลดข้อมูล...',
  NO_DATA: 'ไม่พบข้อมูล',
  LOAD_ERROR: 'ไม่สามารถโหลดข้อมูลได้',
  GENERATE_ERROR: 'ไม่สามารถสร้างเลขเอกสารได้',
  RESET_ERROR: 'ไม่สามารถรีเซ็ตเลขเอกสารได้',
} as const;
