export const TERM_VERSION_DETAIL_MESSAGES = {
  BREADCRUMB_HOME: 'ข้อกำหนดและเงื่อนไข',
  BREADCRUMB_PREFIX: 'รายละเอียด',
  BTN_EDIT_STATUS: 'แก้ไขสถานะ',
  BTN_CREATE_VERSION: 'สร้างเวอร์ชันใหม่ด้วยข้อมูลนี้',
  BTN_EXPORT: 'ส่งออกข้อมูล',
  INFO_VERSION: 'Version',
  INFO_CREATED_BY: 'สร้างโดย',
  INFO_CREATED_AT: 'สร้างเมื่อ',
  INFO_TYPE: 'ประเภท',
  INFO_STATUS: 'สถานะ',
  TYPE_MANDATORY: 'บังคับ',
  STATUS_PUBLISHED: 'Published',
  STATUS_INACTIVE: 'Inactive',
  SECTION_DETAIL: 'รายละเอียด',
  CHECKBOX_LABEL: '* ข้าพเจ้าได้อ่าน ทำความเข้าใจ และยอมรับข้อกำหนดและเงื่อนไขสำหรับใช้งาน รวมถึงนโยบายความเป็นส่วนตัวของธนาคารแล้ว',
  NOT_FOUND: 'ไม่พบข้อมูล',
  MODAL_EDIT_TITLE: 'แก้ไขสถานะ',
  MODAL_STATUS_PUBLISHED: 'Published',
  MODAL_STATUS_PUBLISHED_DESC: 'เผยแพร่ข้อกำหนดให้ลูกค้ายืนยัน',
  MODAL_STATUS_INACTIVE: 'Inactive',
  MODAL_STATUS_INACTIVE_DESC: 'ปิดการใช้งานข้อกำหนดชั่วคราว',
  MODAL_CHANGE_TYPE_LABEL: 'ประเภทการเปลี่ยนแปลงเวอร์ชัน',
  MODAL_CHANGE_TYPE_MAJOR: 'Major — เปลี่ยนเวอร์ชันหลัก',
  MODAL_CHANGE_TYPE_MAJOR_DESC:
    'เช่น v1.0 → v2.0 ผู้ใช้งานต้องยอมรับเงื่อนไขใหม่อีกครั้ง',
  MODAL_CHANGE_TYPE_MINOR: 'Minor — เปลี่ยนเวอร์ชันย่อย',
  MODAL_CHANGE_TYPE_MINOR_DESC:
    'เช่น v1.0 → v1.1 ไม่ต้องให้ผู้ใช้งานยอมรับเงื่อนไขใหม่',
  MODAL_BTN_CANCEL: 'ยกเลิก',
  MODAL_BTN_SAVE: 'บันทึกค่า',
} as const;
