export const WORKFLOW_DOCUMENT_SELECTORS = {
  CONTAINER: 'workflow-doc-container',
  SEARCH_INPUT: 'workflow-doc-search-input',
  BUTTON_SEARCH: 'workflow-doc-button-search',
  NOT_FOUND: 'workflow-doc-not-found',
  HEADER: 'workflow-doc-header',
  TITLE: 'workflow-doc-title',
  DOC_ID: 'workflow-doc-doc-id',
  BIZ_TYPE: 'workflow-doc-biz-type',
  LOADING: 'workflow-doc-loading',
  SECTION_ALL_STEPS: 'workflow-doc-section-all-steps',
  SECTION_CURRENT_STEP: 'workflow-doc-section-current-step',
  STEP_CARD: 'workflow-doc-step-card',
  STEP_NAME: 'workflow-doc-step-name',
  STEP_PROGRESS: 'workflow-doc-step-progress',
  ASSIGNEE_TABLE: 'workflow-doc-assignee-table',
  ACTIONS: 'workflow-doc-actions',
  BUTTON_APPROVE: 'workflow-doc-button-approve',
  BUTTON_REJECT: 'workflow-doc-button-reject',
  BUTTON_FORCE_STOP: 'workflow-doc-button-force-stop',
  BUTTON_EDIT_ASSIGNEE: 'workflow-doc-button-edit-assignee',
  BUTTON_RESUBMIT: 'workflow-doc-button-resubmit',
  ERROR: 'workflow-doc-error',
  MODAL_CONFIRM: 'workflow-doc-modal-confirm',
  MODAL_REMARK: 'workflow-doc-modal-remark',
  MODAL_EDIT_ASSIGNEE: 'workflow-doc-modal-edit-assignee',
  TOAST_SUCCESS: 'workflow-doc-toast-success',
};
