export const WORKFLOW_DOCUMENT_MESSAGES = {
  PAGE_TITLE: 'รายละเอียด Workflow',
  SEARCH_PLACEHOLDER: 'กรอก Document ID เพื่อค้นหา',
  BUTTON_SEARCH: 'ค้นหา',
  NOT_FOUND: 'ไม่พบข้อมูล Workflow สำหรับ Document ID นี้',
  DOC_ID_PREFIX: 'เอกสาร:',
  LOADING: 'กำลังโหลด...',
  SECTION_ALL_STEPS: 'ขั้นตอนทั้งหมด',
  SECTION_CURRENT_STEP: 'ขั้นตอนปัจจุบัน',
  SECTION_STEP_DETAILS: 'รายละเอียดทุก Step',
  STEP_ORDER_PREFIX: 'Step ',
  PROGRESS_APPROVED: 'อนุมัติแล้ว',
  TABLE_COL_ASSIGNEE: 'ผู้รับผิดชอบ',
  TABLE_COL_ROLE: 'Role',
  TABLE_COL_STATUS: 'สถานะ',
  BUTTON_APPROVE_DEFAULT: 'Approve',
  BUTTON_REJECT_DEFAULT: 'Reject',
  BUTTON_FORCE_STOP_DEFAULT: 'Force Stop',
  BUTTON_EDIT_ASSIGNEE: 'แก้ไขผู้รับผิดชอบ',
  BUTTON_RESUBMIT: 'Resubmit',
  MODAL_CANCEL: 'ยกเลิก',
  MODAL_CONFIRM: 'ยืนยัน',
  MODAL_REJECT_CONFIRM: 'ยืนยัน Reject',
  MODAL_SAVE: 'บันทึก',
  MODAL_APPROVE_TITLE: 'ยืนยันการ Approve',
  MODAL_APPROVE_MESSAGE: 'คุณต้องการ Approve ขั้นตอนนี้ใช่หรือไม่?',
  MODAL_FORCE_STOP_TITLE: 'ยืนยันการ Force Stop',
  MODAL_FORCE_STOP_MESSAGE: 'คุณต้องการหยุด Workflow นี้ใช่หรือไม่? กรุณากรอกหมายเหตุ',
  MODAL_REJECT_TITLE: 'Reject — กรุณากรอกเหตุผล',
  MODAL_REMARK_LABEL: 'หมายเหตุ',
  MODAL_REJECT_REASON_LABEL: 'เหตุผล',
  MODAL_REMARK_PLACEHOLDER: 'กรุณากรอกหมายเหตุ',
  MODAL_REJECT_PLACEHOLDER: 'กรุณากรอกเหตุผลในการปฏิเสธ',
  MODAL_EDIT_ASSIGNEE_TITLE: 'แก้ไขผู้รับผิดชอบ',
  MODAL_USER_ID_LABEL: 'User ID',
  MODAL_ROLE_LABEL: 'Role',
  MODAL_ADD_ASSIGNEE: '+ เพิ่มผู้รับผิดชอบ',
  TOAST_ACTION_SUCCESS: 'ดำเนินการสำเร็จ',
  TOAST_REJECT_SUCCESS: 'Reject สำเร็จ',
  TOAST_ASSIGNEE_SUCCESS: 'อัปเดตผู้รับผิดชอบสำเร็จ',
  TOAST_RESUBMIT_SUCCESS: 'Resubmit สำเร็จ',
};
