export const DOCUMENT_NUMBER_API_DEMO_MESSAGES = {
  PAGE_TITLE: 'ตัวอย่างการใช้งาน API เลขเอกสาร',
  PAGE_SUBTITLE:
    'สาธิตการเรียก API สำหรับดูเลขปัจจุบัน, generate, reset และทดสอบหลายคำขอพร้อมกัน',
  POLICY_SEARCH_PLACEHOLDER: 'ค้นหา Policy Code เช่น FX_ENROLLMENT',
  POLICY_LIST_LABEL: 'เลือกรหัสนโยบาย',
  SELECTED_POLICY_LABEL: 'รหัสที่เลือก',
  NO_POLICY_SELECTED: 'กรุณาเลือกรหัสนโยบายก่อนทดสอบ API',
  CURRENT_BUTTON: 'เรียกดู Current',
  GENERATE_BUTTON: 'Generate 1 ครั้ง',
  CONCURRENT_BUTTON: 'Generate พร้อมกัน',
  RESET_BUTTON: 'Reset',
  CONCURRENT_COUNT_LABEL: 'จำนวนคำขอพร้อมกัน',
  RESULT_TITLE: 'ผลลัพธ์ล่าสุด',
  LOG_TITLE: 'API Request / Response Log',
  EMPTY_RESULT: 'ยังไม่มีผลลัพธ์',
  EMPTY_LOG: 'ยังไม่มีการเรียก API',
  SECTION_CURRENT: 'Current Running Number',
  SECTION_GENERATE: 'Generate Result',
  SECTION_CONCURRENT: 'Concurrent Generate Result',
  SECTION_RESET: 'Reset Result',
  STATUS_SUCCESS: 'สำเร็จ',
  STATUS_ERROR: 'ผิดพลาด',
  RESPONSE_LABEL: 'Response',
  REQUEST_LABEL: 'Request',
  API_SAMPLE_TITLE: 'ตัวอย่าง Endpoint',
} as const;
