export const WORKFLOW_APPROVAL_MESSAGES = {
  PAGE_TITLE: 'เอกสารที่รออนุมัติ',
  BUTTON_REFRESH: '↻ รีเฟรช',
  EMPTY_TEXT: 'ไม่มีเอกสารที่รออนุมัติ',
  TABLE_COL_INDEX: '#',
  TABLE_COL_DOC_ID: 'เลขที่เอกสาร',
  TABLE_COL_WORKFLOW_NAME: 'ชื่อ Workflow',
  TABLE_COL_BUSINESS_TYPE: 'ประเภทงาน',
  TABLE_COL_STEP_NAME: 'ขั้นตอน',
  TABLE_COL_POLICY: 'นโยบาย',
  TABLE_COL_CREATED_AT: 'วันที่สร้าง',
  TABLE_COL_STATUS: 'สถานะ',
  TABLE_COL_ACTIONS: 'การดำเนินการ',
  BUTTON_VIEW_DETAIL: 'ดูรายละเอียด',
  BUTTON_APPROVE: 'อนุมัติ',
  BUTTON_REJECT: 'ปฏิเสธ',
  BUTTON_FORCE_STOP: 'หยุด',
  BUTTON_RESUBMIT: 'ส่งใหม่',
  MODAL_CANCEL: 'ยกเลิก',
  MODAL_CONFIRM: 'ยืนยัน',
  DIALOG_DOC_LABEL: 'เอกสาร:',
  DIALOG_STEP_LABEL: 'ขั้นตอน:',
  DIALOG_TYPE_LABEL: 'ประเภท:',
  DIALOG_FORCE_STOP_WARNING: '⚠ การกระทำนี้ไม่สามารถย้อนกลับได้',
  DIALOG_RESUBMIT_NOTE: 'ระบบจะใช้ผู้อนุมัติจาก template เดิม',
  DIALOG_REMARK_LABEL: 'หมายเหตุ',
  DIALOG_REMARK_REQUIRED_SUFFIX: ' *',
  DIALOG_REMARK_PLACEHOLDER: 'ระบุหมายเหตุ...',
  DIALOG_APPROVE_TITLE: 'ยืนยันการอนุมัติ',
  DIALOG_APPROVE_LABEL: 'อนุมัติ',
  DIALOG_REJECT_TITLE: 'ยืนยันการปฏิเสธ',
  DIALOG_REJECT_LABEL: 'ปฏิเสธ',
  DIALOG_FORCE_STOP_TITLE: '⚠ หยุด Workflow',
  DIALOG_FORCE_STOP_LABEL: 'ยืนยันหยุด Workflow',
  DIALOG_RESUBMIT_TITLE: 'ส่งเอกสารใหม่อีกครั้ง',
  DIALOG_RESUBMIT_LABEL: 'ส่งอีกครั้ง',
  TOAST_LOAD_ERROR: 'ไม่สามารถโหลดข้อมูลได้ กรุณาลองอีกครั้ง',
  TOAST_WORKFLOW_LOAD_ERROR: 'ไม่สามารถโหลดข้อมูล workflow ได้',
  TOAST_ACTION_ERROR: 'เกิดข้อผิดพลาด กรุณาลองอีกครั้ง',
  TOAST_APPROVE_SUCCESS: 'อนุมัติเอกสารสำเร็จ',
  TOAST_REJECT_SUCCESS: 'ปฏิเสธเอกสารสำเร็จ',
  TOAST_FORCE_STOP_SUCCESS: 'หยุด Workflow สำเร็จ',
  TOAST_RESUBMIT_SUCCESS: 'ส่งเอกสารใหม่สำเร็จ',
  TOAST_DEFAULT_SUCCESS: 'ดำเนินการสำเร็จ',
  REMARK_REQUIRED_ERROR: 'กรุณาระบุเหตุผล',
};
